env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  { "import/prefer-default-export": "off", "import/no-default-export": "error" }
