env:
  browser: true
  es2021: true
extends: ['airbnb', 'prettier']
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  { 'import/prefer-default-export': 'off', 'import/no-default-export': 'error' }
